#!/bin/sh

STAGED_FILES=$(git diff --name-only --cached --diff-filter=AM | grep '\.py')
if [ -z "$STAGED_FILES" ]; then
    exit 0
fi

CHANGES_TO_STAGED_FILES=$(git diff --name-only -- ${STAGED_FILES})
if [ -n "${CHANGES_TO_STAGED_FILES}" ]; then
    echo "The following staged files have uncommited changes:"
    echo "${CHANGES_TO_STAGED_FILES[@]}"
    echo "Commit aborted."
    exit 1
fi

isort ${STAGED_FILES}
autoflake --in-place --remove-all-unused-imports --remove-unused-variables ${STAGED_FILES}
black ${STAGED_FILES}

REFORMATED_FILES=$(git diff --name-only -- ${STAGED_FILES})
if [ -n "${REFORMATED_FILES}" ]; then
    git add ${REFORMATED_FILES}
fi