version: '3.7'

services:
  webapp:
    image: webapp:latest
    build: ./webapp
    command: python front_end/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./spending_tree/:/usr/src/spending_tree/
    ports:
      - 8000:8000
    env_file:
      - ./.envcd

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: